POST http://localhost:9000/todo/ HTTP/1.1
content-type: application/json

{
    "title": "My first Todo",
    "description": "First description",
    "is_done": false
}

###

GET http://localhost:9000/todo/ HTTP/1.1
content-type: application/json

###

GET http://localhost:9000/todo/2 HTTP/1.1
content-type: application/json

###

PUT http://localhost:9000/todo/2 HTTP/1.1
content-type: application/json

{
    "title": "My first Todo editado",
    "description": "First description editado",
    "is_done": true
}

###

DELETE http://localhost:9000/todo/2 HTTP/1.1
content-type: application/json
